# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x05\x63loud\".\n\x10OperationRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"#\n\x11OperationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xae\x02\n\nCalculator\x12\x38\n\x03\x41\x64\x64\x12\x17.cloud.OperationRequest\x1a\x18.cloud.OperationResponse\x12\x38\n\x03Sub\x12\x17.cloud.OperationRequest\x1a\x18.cloud.OperationResponse\x12\x38\n\x03Mul\x12\x17.cloud.OperationRequest\x1a\x18.cloud.OperationResponse\x12\x38\n\x03\x44iv\x12\x17.cloud.OperationRequest\x1a\x18.cloud.OperationResponse\x12\x38\n\x03Mod\x12\x17.cloud.OperationRequest\x1a\x18.cloud.OperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONREQUEST']._serialized_start=27
  _globals['_OPERATIONREQUEST']._serialized_end=73
  _globals['_OPERATIONRESPONSE']._serialized_start=75
  _globals['_OPERATIONRESPONSE']._serialized_end=110
  _globals['_CALCULATOR']._serialized_start=113
  _globals['_CALCULATOR']._serialized_end=415
# @@protoc_insertion_point(module_scope)
